name: generate_full_docs
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate_docs:
    name: Generate Docs
    runs-on: macos-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Select the latest Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest'

    - name: Setup Ruby 3.3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
        bundler-cache: true

    - name: Install Fastlane and Jazzy using gem
      run: |
        gem install fastlane
        gem install jazzy

    - name: Install SourceDocs using Homebrew
      run: |
        brew install sourcedocs

    - name: Install dependencies (Pods)
      run: |
        pod install

    - name: Run Fastlane to generate full documentation
      run: |
        fastlane generate_full_docs

    - name: Setup Git user (GitHub Actions bot)
      run: |
        git config user.name TelnyxIntegrations
        git config user.email integrations@telnyx.com

    - name: Configure git push.autoSetupRemote
      run: |
        git config push.autoSetupRemote true

    - name: Create new branch name for docs
      run: |
        BRANCH_NAME="docs/update-$(date +'%Y%m%d%H%M%S')"
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Create Pull Request using GitHub Actions bot
      uses: peter-evans/create-pull-request@v7
      with:
        add-paths: |
          docs/
          docs-markdown/
        token: ${{ secrets.GITHUB_TOKEN }}
        committer: TelnyxIntegrations <integrations@telnyx.com>
        base: main
        branch: ${{ env.branch_name }}
        delete-branch: true
        title: '[docs] Update generated HTML and Markdown documentation'
        commit-message: "docs: Generated full documentation"
        body: "This PR updates the full documentation generated by Fastlane using Jazzy and SourceDocs."
        labels: "documentation, auto-generated"
        draft: false
