name: generate_full_docs
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate_docs:
    name: Generate Docs
    runs-on: macos-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main  # Aseguramos que estamos trabajando con la rama main

    - name: Select the latest Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest'  # Use the latest version de Xcode disponible en GitHub Actions

    - name: Setup Ruby 3.3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
        bundler-cache: true

    - name: Install Fastlane and Jazzy using gem
      run: |
        gem install fastlane
        gem install jazzy

    - name: Install SourceDocs using Homebrew
      run: |
        brew install sourcedocs

    - name: Install dependencies (Pods)
      run: |
        pod install

    - name: Run Fastlane to generate full documentation
      run: |
        fastlane generate_full_docs

    - name: Setup Git user
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

    - name: Commit and push docs
      run: |
        git add docs/ docs_markdown/
        git commit -m "docs: Generated full documentation"
        git push
