# This workflow deploys the latest SDK version to CocoaPods using the `.podspec` configuration.
#
# 📋 Steps:
# 1. Checks out the repository with full history to ensure access to tags.
# 2. Sets up Ruby 2.7.4 and installs dependencies using Bundler.
# 3. Installs Fastlane, which is used for changelog generation.
# 4. Retrieves the second-to-last created Git tag to use as the base for the changelog.
# 5. Generates a changelog using Fastlane based on commits since the last release tag.
# 6. Reads and prints the changelog contents for visibility in the job logs.
# 7. Runs `pod lib lint` to validate the `.podspec` file.
# 8. Publishes the SDK to the CocoaPods trunk using the `pod trunk push` command with authentication.
name: release-04-deploy-cocoapods
on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
    
jobs:
  build:
    name: release_deploy_cocoapods
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

    - name: "🤖 Setup ruby"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.4
        bundler-cache: true

    - name: "🤖 Setup Fastlane"
      run:  |
          bundle install

    - name: "✏️ Get previous created TAG"
      id: get-previous-tag
      run:  echo "::set-output name=LAST_TAG::$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))"

    - name: "✏️  Generate changelog from previous TAG and HEAD"
      id: get-changelog
      run: |
          bundle exec fastlane changelog tag:${{ steps.get-previous-tag.outputs.LAST_TAG }}

    - name: "✏️ Read changelog.txt"
      id: changelog-file
      uses: juliangruber/read-file-action@v1
      with:
        path: ./fastlane/changelog.txt

    - name: "✏️ Print Changelog"
      run: |
          echo "${{ steps.changelog-file.outputs.content }}"

    - name: "🤖 Podspec lint"
      run: |
        pod lib lint --allow-warnings

    - name: "🚀  Publish to CocoaPods register"
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push TelnyxRTC.podspec --allow-warnings

