name: tests-ui-sample-app-firebase

on:
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4.0'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Install dependencies
        run: pod install

      - name: Decode and create GoogleService-Info.plist
        run: echo $TEST_UI_FIREBASE_PLIST_BASE64 | base64 --decode > TelnyxWebRTCDemo/GoogleService-Info.plist

      - name: Set up environment
        run: |
          sh setup_uitest_env.sh \
            -u "${{ secrets.TEST_UI_SIP_USER }}" \
            -p "${{ secrets.TEST_UI_SIP_PASSWORD }}" \
            -t "${{ secrets.TEST_UI_SIP_TOKEN }}" \
            -d "${{ secrets.TEST_UI_DESTINATION_NUMBER }}"
            -c "${{ secrets.TEST_IU_CALLER_NUMBER }}"

      - name: Install Google Cloud SDK
        run: |
          brew install google-cloud-sdk
          gcloud components install firebase-test

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.TEST_UI_GCLOUD_SERVICE_KEY }}" | gcloud auth activate-service-account --key-file=-
          gcloud config set project ${{ secrets.TEST_UI_GCLOUD_PROJECT_ID }}

      - name: Build UI Tests
        run: |
          xcodebuild build-for-testing \
            -workspace TelnyxWebRTCDemo.xcworkspace \
            -scheme TelnyxWebRTCDemo \
            -sdk iphoneos \
            -configuration Debug \
            -derivedDataPath build

      - name: Create test zip
        run: |
          TEST_RUN_FILE=$(find build/Build/Products -name "*.xctestrun" | head -n 1)
          zip -r TelnyxWebRTCDemoUITests.zip \
              build/Build/Products/Debug-iphoneos \
              "$TEST_RUN_FILE"

      - name: Run tests on Firebase Test Lab
        run: |
          gcloud firebase test ios run \
            --test TelnyxWebRTCDemoUITests.zip \
            --device model=iphone14pro,version=16.6,locale=en_US,orientation=portrait
